org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official

# LibGDX version
gdxVersion=1.12.1
roboVMVersion=2.3.20
box2DLightsVersion=1.5
ashleyVersion=1.7.4
aiVersion=1.8.2

# Room
roomVersion=2.8.4
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.enableR8.fullMode=false
android.r8.optimizedResourceShrinking=false
android.useSeparateJniLibPackaging=true
android.builtInKotlin=false
android.newDsl=false
